config/routes.rb
Onepager::Application.routes.draw do
  root :to => 'static#index'
  
  resources :sites, :only => [:create, :show] do
    resources :pages, :only => [:show, :edit, :update] do
      member do
        put 'update_positions'
      end
    end
  end
  
  resource :signin, :controller => "user_sessions", :only => [:new, :create, :destroy], :path_names => { :new => "" }
  resource 'reset-password', :as => :reset_password, :controller => :reset_password, :only => [:new, :create, :edit, :update], :path_names => { :new => "" }
  resource :signup, :controller => "users", :only => [:new, :create], :path_names => { :new => "" } do
    collection do
      get 'get_city_state'
      get 'check_domain_availability'
      get 'validate_promo_code'
      get 'thankyou'
      post 'thankyou_survey'
    end
  end
  
  resources :themes, :only => [:show]
  
  resources :subscribers, :only => [:create] do
    member do
      get 'subscribe'
      get 'unsubscribe'
    end
  end
  post 'contact_form_responses' => 'contact_form_responses#create'
  post 'promotion_responses' => 'promotion_responses#create'
  
  get 'custom/:id.css' => 'pages#css'
  get 'custom/:id.ie.css' => 'pages#css_ie'
  
  namespace :dashboard do
    root :to => 'analytics#show'
    resource :newsletter, :only => [:new, :create], :path_names => { :new => "" } do
      collection do
        post 'confirm'
      end
    end
    get 'forms' => 'forms#index'
    get 'forms/:id' => 'forms#show'
    resources :subscribers, :only => [:index]
    resource :setting, :only => [:edit, :update, :destroy], :path_names => { :edit => "" }
    resource :domain, :controller => "sites", :only => [:edit, :update], :path_names => { :edit => "" } do
      put 'update_free_domain_user' => 'sites#update_free_domain_user'
    end
    get 'sites/:site_id/export' => 'sites#export'
  end
  
  namespace :account do
    resources :sites, :only => [:index, :create, :destroy]
    resource :affiliate, :only => [:show, :new, :create]
    
    get 'upgrade' => 'users#upgrade'
    put 'upgrade' => 'users#upgrade_update'
    post 'feedback' => 'users#feedback_send'
    
    resources :users, :except => [:show]
    resource :billing, :only => [:edit, :update]
    resources :billing, :controller => :billings, :only => [:index, :show]
    resource :settings, :only => [:edit, :update], :path_names => { :edit => "" }
    resource :whitelabel, :only => [:edit, :update], :path_names => { :edit => "" }
  end
  
  namespace :content_types do
    resources :buttons, :only => [:new, :create, :update, :destroy]
    resources :contact_form_fields, :only => [:new, :create, :update, :destroy]
    resources :contact_sections, :only => [:new, :create, :update, :destroy]
    resources :download_sections, :only => [:new, :create, :update, :destroy]
    resources :downloads, :only => [:create]
    resources :embeds, :only => [:new, :create, :update, :destroy]
    resources :galleries, :only => [:new, :create, :update, :destroy]
    resources :gallery_images, :only => [:create]
    resources :hours, :only => [:new, :create, :update, :destroy]
    resources :newsletters, :only => [:new, :create, :update, :destroy]
    resources :services, :only => [:new, :create, :update, :destroy]
    resources :social_buttons, :only => [:new, :create, :update, :destroy]
    resources :social_feeds, :only => [:new, :create, :update, :destroy]
    resources :text_areas, :only => [:new, :create, :update, :destroy]
    resources :products, :only => [:new, :create, :update, :destroy]
    resources :iframes, :only => [:new, :create, :update, :destroy]
    resources :script_embeds, :only => [:new, :create, :update, :destroy]
    resources :paypal_buttons, :only => [:new, :create, :update, :destroy]
    resources :promotions, :only => [:new, :create, :update, :destroy]
  end
  
  match 'en/:pagename' => 'static#show'
  match 'en/:section/:pagename' => 'static#show'
  
  namespace :opgadmin do
    root :to => redirect("/opgadmin/users")
    resources :themes, :except => [:show] do
      put 'update_positions', :on => :collection
    end
    resources :users, :only => [:index, :show, :destroy, :edit, :update] do
      post 'cancel', :on => :member
      post 'activate', :on => :member
      post 'signin_as', :on => :member
    end
    resources :sites, :only => [:destroy] do
      post 'activate', :on => :member
      post 'clone', :on => :member
      post 'dont_renew_domain', :on => :member
    end
  end

  post '/api/users' => 'api#create_user'
  match 'api/paypal_callback' => 'api#paypal_callback'
  
  get '/sitemap' => 'static#sitemap'
  get '/sitemaps/:id' => 'static#sitemaps'
  get '/robots' => 'static#robots'
  get ':onepager_address' => 'pages#show'
  

end

app/views/shared/_adroll.html.erb
<script type="text/javascript">
	adroll_adv_id = "OI3IASZAYNAONC44W7XUSJ";
	adroll_pix_id = "HYH5BRZSWRHZ3F7JCIYCAV";
	(function () {
	var oldonload = window.onload;
	window.onload = function(){
	   __adroll_loaded=true;
	   var scr = document.createElement("script");
	   var host = (("https:" == document.location.protocol) ? "https://s.adroll.com" : "http://a.adroll.com");
	   scr.setAttribute('async', 'true');
	   scr.type = "text/javascript";
	   scr.src = host + "/j/roundtrip.js";
	   ((document.getElementsByTagName('head') || [null])[0] ||
	    document.getElementsByTagName('script')[0].parentNode).appendChild(scr);
	   if(oldonload){oldonload()}};
	}());
</script>

app/views/shared/_dashboard_footer.html.erb
<footer>
	<section>
		<nav>
			<a href="/en/resources/guides">Guides</a>
			<a href="/en/resources/how-to-videos">How-To Videos</a>
			<a href="/en/resources/faq">FAQ</a>
			<a href="/en/contact-us">Contact Us</a>
			<a href="/blog">Blog</a>
			<a href="/en/legal/privacy-policy">Privacy Policy</a>
			<a href="/en/legal/terms-conditions">Terms &amp; Conditions</a>
		</nav>
		<img src="/assets/dashboard/logo-footer.png" alt="Onepager" />
	</section>
	<section>
		<a href="http://facebook.com/onepager"><img src="/assets/application/facebook.png" alt="Facebook" /></a>
		<a href="http://twitter.com/onepagerapp"><img src="/assets/application/twitter.png" alt="Twitter" /></a>
		<span>&copy; 2016 Onepager Inc.</span>
	</section>
</footer>

app/views/shared/_google_analytics.html.erb
<script type="text/javascript">
	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', 'UA-24551289-1']);
	_gaq.push(['_setDomainName', 'none']);
	_gaq.push(['_setAllowLinker', true]);
	_gaq.push(['_trackPageview']);
	
	(function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	})();
</script>

app/views/shared/_gumroad_message.html.erb
<div class="gumroad_message" style="display: none;">
	<h4>Congratulations on setting up your Onepager to put money in your pocket!</h4>
	<img src="/assets/pages/onboarding/logo-gumroad.png" alt="Gumroad" />
	<p>Keep an eye open for emails from our partner, <a href="http://gumroad.com" target="_blank">Gumroad</a>. All Onepager transactions are processed through them and they’ll email you whenever you have money coming your way.</p>
	<p>Good luck with your sales and as always, shoot us an email at <a href="mailto:support@onepagerapp.com">support@onepagerapp.com</a> if we can help in any way.</p>
</div>

app/views/shared/_hittail.html.erb
<!-- HitTail Code -->
<script type="text/javascript">
	(function(){ var ht = document.createElement('script');ht.async = true;
	  ht.type='text/javascript';ht.src = '//95393.hittail.com/mlt.js';
	  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ht, s);})();
</script>

app/views/shared/_multisites_message.html.erb
<div class="reminder_dialog" style="display: none;">
	<h4>You've successfully created a new Onepager website!</h4>
	<p>Your temporary Onepager Address is <a href="<%= @site.url_fullpath %>" target="_blank">onepagerapp.com/<%= @site.onepager_address %></a>. To change your Onepager Address or set a custom domain, go to your <a href="/dashboard/domain">Domain setting</a> page.</p>
	<img src="/assets/pages/onboarding/domain-reminder.png" alt="Custom Domain" />
</div>

app/views/shared/_olark.html.erb
<script data-cfasync="false" type='text/javascript'>/*{literal}<![CDATA[*/
window.olark||(function(c){var f=window,d=document,l=f.location.protocol=="https:"?"https:":"http:",z=c.name,r="load";var nt=function(){f[z]=function(){(a.s=a.s||[]).push(arguments)};var a=f[z]._={},q=c.methods.length;while(q--){(function(n){f[z][n]=function(){f[z]("call",n,arguments)}})(c.methods[q])}a.l=c.loader;a.i=nt;a.p={0:+new Date};a.P=function(u){a.p[u]=new Date-a.p[0]};function s(){a.P(r);f[z](r)}f.addEventListener?f.addEventListener(r,s,false):f.attachEvent("on"+r,s);var ld=function(){function p(hd){hd="head";return["<",hd,"></",hd,"><",i,' onl' + 'oad="var d=',g,";d.getElementsByTagName('head')[0].",j,"(d.",h,"('script')).",k,"='",l,"//",a.l,"'",'"',"></",i,">"].join("")}var i="body",m=d[i];if(!m){return setTimeout(ld,100)}a.P(1);var j="appendChild",h="createElement",k="src",n=d[h]("div"),v=n[j](d[h](z)),b=d[h]("iframe"),g="document",e="domain",o;n.style.display="none";m.insertBefore(n,m.firstChild).id=z;b.frameBorder="0";b.id=z+"-loader";if(/MSIE[ ]+6/.test(navigator.userAgent)){b.src="javascript:false"}b.allowTransparency="true";v[j](b);try{b.contentWindow[g].open()}catch(w){c[e]=d[e];o="javascript:var d="+g+".open();d.domain='"+d.domain+"';";b[k]=o+"void(0);"}try{var t=b.contentWindow[g];t.write(p());t.close()}catch(x){b[k]=o+'d.write("'+p().replace(/"/g,String.fromCharCode(92)+'"')+'");d.close();'}a.P(2)};ld()};nt()})({loader: "static.olark.com/jsclient/loader0.js",name:"olark",methods:["configure","extend","declare","identify"]});
/* custom configuration goes here (www.olark.com/documentation) */
olark.identify('4591-490-10-3671');/*]]>{/literal}*/</script>

app/views/shared/_onboarding.html.erb
<div class="onboarding" style="display: none;">
	<dl>
		<dt>Build</dt>
		<dd>
			<img src="/assets/pages/onboarding/build-edit.png" alt="Edit" />
			<p>Click on the content you’d like to <strong>edit</strong></p>
		</dd>
		<dd>
			<img src="/assets/pages/onboarding/build-add.png" alt="Add" />
			<p>Click <strong>Add Content</strong> to add something new</p>
		</dd>
	</dl>
	<dl>
		<dt>Customize</dt>
		<dd>
			<img src="/assets/pages/onboarding/customize.png" alt="Customize" />
			<p>Choose a theme, make your own, or change the page layout in the editor panel.</p>
		</dd>
	</dl>
	<dl>
		<dt>Launch</dt>
		<dd>
			<img src="/assets/pages/onboarding/launch.png" alt="Launch" />
			<p>Click <strong>Next</strong> to finish setting up your account and launch your Onepager!</p>
		</dd>
	</dl>
</div>

app/views/shared/_toolbar.html.erb
<section class="toolbar">
	<nav>
		<% if current_user.payment_plan == "Child" && current_user.white_label_title == "Onepager" %>
			<%= link_to image_tag('dashboard/logo-toolbar.png'), account_sites_path, :class => 'logo' %>
		<% elsif current_user.payment_plan == "Child" && current_user.white_label_title != "Onepager" %>
			<%= link_to current_user.white_label_title, account_sites_path, :class => 'logo' %>
		<% else %>
			<%= link_to image_tag('dashboard/logo-toolbar.png'), account_sites_path, :class => 'logo' %>
		
			<div class="question_dropdown">
				<a href="#" class="feedback">As A Question</a>
				<div class="dropdown">
					<%= form_tag account_feedback_path, :remote => true do %>
						<%= label_tag 'feedback', 'Ask us a question or provide feedback:' %>
						<%= text_area_tag 'feedback' %>
						<%= submit_tag "Submit", :class => 'start' %>
					<% end %>
				</div>
			</div>
		<% end %>
		<div class="account_dropdown">
			<%= link_to 'Account', '/account/settings' %>
			<div class="dropdown">
				<%= link_to 'Profile', '/account/settings' %>
				<%= link_to 'Users', account_users_path if current_user.paying_user? %>
				<%= link_to 'Billing', '/account/billing' if current_user.paying_user? %>
				<%= link_to 'Affiliates', account_affiliate_path if current_user.payment_plan != 'Child' %>
				<%= link_to 'Private Label', account_whitelabel_path if current_user.paying_user? %>
				<%= link_to 'Sign Out', signin_path, :method => :delete %>
			</div>
		</div>
	</nav>
</section>

app/views/shared/_toolbox.html.erb
<section class="toolbox" style="height: 38px;">
	
	<%= form_for @site, :url => site_page_path(@site, @page), :remote => true, :html => { :enctype => "multipart/form-data" } do |f| %>
		<nav>
			<a href="#" class="button_show">Show</a>
			<a href="#" data-section="theme" class="button_theme">Theme</a>
			<a href="#" data-section="styles" class="button_styles">Styles</a>
			<a href="#" data-section="layout" class="button_layout">Layout</a>
			<div class="form_actions">
				<input type="hidden" name="section" value="theme" />
				<%= link_to 'Get More Features!', account_upgrade_path, :class => 'upgrade' if current_user && current_user.payment_frequency == "Trial" %>
				<% unless request.domain == "easysiteadmin.com" and @site.user_id.blank? %>
					<%= f.submit ( current_user ? 'Save' : 'Next' ), :class => 'user_submit save_page' %>
				<% end %>
				<%= f.submit 'Save & Close', :class => 'user_submit close_page' if current_user %>
			</div>
		</nav>
		<fieldset class="theme" style="display: none;">
			<div class="theme_collection">
				<ul>
					<li><a href="#" data-id="custom" class="theme_custom"><img src="/assets/pages/toolbox/icon-custom.png?1" alt="Custom" /></a></li>
					<%# Temp iterator %>
					<% @themes.each do |t| %>
						<li><%= link_to image_tag(t.screenshot_image, :alt => ''), theme_path(t), :remote => true, 'data-type' => 'json' %></li>
					<% end %>
				</ul>
			</div>
			<div class="theme_limiter">
				<a href="#" data-direction="left">Previous</a>
				<a href="#" data-direction="right">Next</a>
			</div>
			<%= f.hidden_field :theme_id %>
		</fieldset>
		<fieldset class="styles" style="display: none;">
			
			<div class="background_body">
				<%= f.label :background_colour, 'Page Background' %>
				<span class="colorpicker" data-element="body" data-field="background_colour">
					<a href="#" style="background-color: #<%= @site.background_colour %>;">Colors</a>
				</span>
				<% if @site.background_image.blank? || !@site.background_image_enabled %>
					<%= f.select :background_image_alignment, Site::ALIGNMENTS, {}, { :disabled => 'disabled', 'data-element' => 'body' } %>
					<%= f.file_field :background_image %>
					<p style="display: none;">
						<%= f.check_box :background_image_fixed %>
						<%= f.label :background_image_fixed, 'Fixed in place' %>
						<a href="#" class="disable_background_image">Remove/Change Image</a>
					</p>
				<% else %>
					<%= f.select :background_image_alignment, Site::ALIGNMENTS, {}, { 'data-element' => 'body'} %>
					<%= f.file_field :background_image, :style => 'display: none;' %>
					<p>
						<%= f.check_box :background_image_fixed %>
						<%= f.label :background_image_fixed, 'Fixed in place' %>
						<a href="#" class="disable_background_image">Remove/Change Image</a>
					</p>
				<% end %>
			</div>
			
			<div class="background_content">
				<%= f.label :content_background_colour, 'Content Background' %>
				<span class="colorpicker" data-element="article" data-field="content_background_colour">
					<a href="#" style="background-color: #<%= @site.content_background_colour %>;">Colors</a>
				</span>
				<span class="scrollbar" data-element="article" data-name="content_background_opacity" data-value="<%= @site.content_background_opacity %>">&nbsp;</span>
			</div>
			
			<div class="fontsets">
				<ul>
					<li>
						<%= f.label :header_type, 'Company Font' %>
						<%= f.select :header_type, font_select(), {}, {'data-element' => 'h1'} %>
						<span class="colorpicker" data-element="h1" data-field="header_colour">
							<a href="#" style="background-color: #<%= @site.header_colour %>;">Colors</a>
						</span>
						<span class="scrollbar" data-element="h1" data-name="header_size" data-value="<%= @site.header_size %>">&nbsp;</span>
					</li>
					<li>
						<%= f.label :subheader_type, 'Header Font' %>
						<%= f.select :subheader_type, font_select(), {}, {'data-element' => 'h2,h3'} %>
						<span class="colorpicker" data-element="h2,h3" data-field="subheader_colour">
							<a href="#" style="background-color: #<%= @site.subheader_colour %>;">Colors</a>
						</span>
						<span class="scrollbar" data-element="h2" data-name="subheader_size" data-value="<%= @site.subheader_size %>">&nbsp;</span>
					</li>
					<li>
						<%= f.label :body_type, 'Body Font' %>
						<%= f.select :body_type, font_select( Site::FONTS['safe'] + Site::FONTS['basic'] ), {}, {'data-element' => 'body'} %>
						<span class="colorpicker" data-element="body" data-field="body_colour">
							<a href="#" style="background-color: #<%= @site.body_colour %>;">Colors</a>
						</span>
						<span class="scrollbar" data-element="body" data-name="body_size" data-value="<%= @site.body_size %>">&nbsp;</span>
					</li>
				</ul>
			</div>
			
			<%= f.hidden_field :remote_background_image_url %>
			<%= f.hidden_field :content_background_colour %>
			<%= f.hidden_field :content_background_opacity %>
			<%= f.hidden_field :background_colour %>
			<%= f.hidden_field :background_image_enabled %>
			<%= f.hidden_field :header_colour %>
			<%= f.hidden_field :header_size %>
			<%= f.hidden_field :subheader_colour %>
			<%= f.hidden_field :subheader_size %>
			<%= f.hidden_field :body_colour %>
			<%= f.hidden_field :body_size %>
			
		</fieldset>
		<fieldset class="layout" style="display: none;">
			<%= f.fields_for :pages do |p| %>
			
				<div class="layout_settings">
					<%= p.label :layout_alignment, 'Position' %>
					<% ['left', 'none', 'right'].each do |a| %>
						<a href="#" data-value="<%= a %>" data-name="layout_alignment"<%=raw ' class="enabled"' if @page.layout_alignment == a %>>
							<img src="/assets/pages/toolbox/layout-alignment-<%= a %>.png" alt="<%= a %>" />
						</a>
					<% end %>
				</div>
				<div class="layout_settings">
					<%= p.label :layout_width, 'Columns' %>
					<% ['450', '650', '835'].each do |a| %>
						<a href="#" data-value="<%= a %>" data-name="layout_width"<%=raw ' class="enabled"' if @page.layout_width == a %>>
							<img src="/assets/pages/toolbox/layout-width-<%= a %>.png" alt="<%= a %>" />
						</a>
					<% end %>
				</div>
				
				<%= p.hidden_field :layout_width %>
				<%= p.hidden_field :layout_alignment %>
			<% end %>
		</fieldset>
	<% end %>
</section>

app/views/shared/_widget.html.erb
<section class="widget" style="display: none;">
	<div class="widget_header">
		<h6>What would you like to add here?</h6>
		<a href="#" class="form_close">Info</a>
	</div>
	<div class="widget_contents">
		<%= link_to new_content_types_text_area_path(:page_id => @page.id, :position => ""), :remote => true do %>
			<img src="/assets/pages/widget/textarea.png" alt="Text" />
			Text
		<% end %>
		<%= link_to new_content_types_service_path(:page_id => @page.id, :position => ""), :remote => true do %>
			<img src="/assets/pages/widget/services.png" alt="Services" />
			Services
		<% end %>
		<%= link_to new_content_types_button_path(:page_id => @page.id, :position => ""), :remote => true do %>
			<img src="/assets/pages/widget/button.png" alt="Button" />
			Button
		<% end %>
		<%= link_to new_content_types_contact_section_path(:page_id => @page.id, :position => ""), :remote => true do %>
			<img src="/assets/pages/widget/contact.png" alt="Contact" />
			Contact
		<% end %>
		<%= link_to new_content_types_embed_path(:page_id => @page.id, :position => ""), :remote => true do %>
			<img src="/assets/pages/widget/media.png" alt="Media" />
			Media
		<% end %>
		<%= link_to new_content_types_hour_path(:page_id => @page.id, :position => ""), :remote => true do %>
			<img src="/assets/pages/widget/hours.png" alt="Hours" />
			Hours
		<% end %>
		<%= link_to new_content_types_social_button_path(:page_id => @page.id, :position => ""), :remote => true do %>
			<img src="/assets/pages/widget/social.png" alt="Social" />
			Social
		<% end %>
		<%= link_to new_content_types_newsletter_path(:page_id => @page.id, :position => ""), :remote => true do %>
			<img src="/assets/pages/widget/newsletter.png" alt="Newsletter" />
			Newsletter
		<% end %>
		<%= link_to new_content_types_gallery_path(:page_id => @page.id, :position => ""), :remote => true do %>
			<img src="/assets/pages/widget/images.png" alt="Images" />
			Images
		<% end %>
		<%= link_to new_content_types_download_section_path(:page_id => @page.id, :position => ""), :remote => true do %>
			<img src="/assets/pages/widget/downloads.png" alt="Downloads" />
			Downloads
		<% end %>
		<% if !current_user %>
			<span class="disabled" title="Sign up to unlock this feature "><img src="/assets/pages/widget/form.png" alt="Form" />Form</span>
			<span class="disabled" title="Sign up to unlock this feature "><img src="/assets/pages/widget/sell.png?1" alt="PayPal Button" />PayPal Button</span>
		<% else %>
			<% if current_user.payment_frequency == 'Trial' %>
				<a href="/account/upgrade" class="disabled" title="Upgrade to unlock this feature "><img src="/assets/pages/widget/form.png" alt="Form" />Form</a>
				<a href="/account/upgrade" class="disabled" title="Upgrade to unlock this feature "><img src="/assets/pages/widget/sell.png?1" alt="PayPal Button" />PayPal Button</a>
			<% else %>
				<%= link_to new_content_types_contact_form_field_path(:page_id => @page.id, :position => ""), :remote => true do %>
					<img src="/assets/pages/widget/form.png" alt="Form" />
					Form
				<% end %>
				<%= link_to new_content_types_paypal_button_path(:page_id => @page.id, :position => ""), :remote => true do %>
					<img src="/assets/pages/widget/sell.png?1" alt="Paypal" />
					Paypal
				<% end %>
			<% end %>
		<% end %>
		<%= link_to new_content_types_social_feed_path(:page_id => @page.id, :position => ""), :remote => true do %>
			<img src="/assets/pages/widget/feeds.png" alt="Feed" />
			Feed
		<% end %>
		<%= link_to new_content_types_iframe_path(:page_id => @page.id, :position => ""), :remote => true do %>
			<img src="/assets/pages/widget/iframe.png" alt="iframe" />
			iframe
		<% end %>
		<% if current_user %>
			<%= link_to new_content_types_promotion_path(:page_id => @page.id, :position => ""), :remote => true do %>
				<img src="/assets/pages/widget/promotion.png" alt="Promotion" />
				Promotion
			<% end %>
		<% end %>
		
		<% if (@site.user && @site.user.allow_script_embeds?) %>
			<%= link_to new_content_types_script_embed_path(:page_id => @page.id, :position => ""), :remote => true do %>
				<img src="/assets/pages/widget/embed.png" alt="iframe" />
				Embed
			<% end %>
		<% end %>
	</div>
</section>