config/routes.rb
Onepager::Application.routes.draw do
  root :to => 'static#index'
  
  resources :sites, :only => [:create, :show] do
    resources :pages, :only => [:show, :edit, :update] do
      member do
        put 'update_positions'
      end
    end
  end
  
  resource :signin, :controller => "user_sessions", :only => [:new, :create, :destroy], :path_names => { :new => "" }
  resource 'reset-password', :as => :reset_password, :controller => :reset_password, :only => [:new, :create, :edit, :update], :path_names => { :new => "" }
  resource :signup, :controller => "users", :only => [:new, :create], :path_names => { :new => "" } do
    collection do
      get 'get_city_state'
      get 'check_domain_availability'
      get 'validate_promo_code'
      get 'thankyou'
      post 'thankyou_survey'
    end
  end
  
  resources :themes, :only => [:show]
  
  resources :subscribers, :only => [:create] do
    member do
      get 'subscribe'
      get 'unsubscribe'
    end
  end
  post 'contact_form_responses' => 'contact_form_responses#create'
  post 'promotion_responses' => 'promotion_responses#create'
  
  get 'custom/:id.css' => 'pages#css'
  get 'custom/:id.ie.css' => 'pages#css_ie'
  
  namespace :dashboard do
    root :to => 'analytics#show'
    resource :newsletter, :only => [:new, :create], :path_names => { :new => "" } do
      collection do
        post 'confirm'
      end
    end
    get 'forms' => 'forms#index'
    get 'forms/:id' => 'forms#show'
    resources :subscribers, :only => [:index]
    resource :setting, :only => [:edit, :update, :destroy], :path_names => { :edit => "" }
    resource :domain, :controller => "sites", :only => [:edit, :update], :path_names => { :edit => "" } do
      put 'update_free_domain_user' => 'sites#update_free_domain_user'
    end
    get 'sites/:site_id/export' => 'sites#export'
  end
  
  namespace :account do
    resources :sites, :only => [:index, :create, :destroy]
    resource :affiliate, :only => [:show, :new, :create]
    
    get 'upgrade' => 'users#upgrade'
    put 'upgrade' => 'users#upgrade_update'
    post 'feedback' => 'users#feedback_send'
    
    resources :users, :except => [:show]
    resource :billing, :only => [:edit, :update]
    resources :billing, :controller => :billings, :only => [:index, :show]
    resource :settings, :only => [:edit, :update], :path_names => { :edit => "" }
    resource :whitelabel, :only => [:edit, :update], :path_names => { :edit => "" }
  end
  
  namespace :content_types do
    resources :buttons, :only => [:new, :create, :update, :destroy]
    resources :contact_form_fields, :only => [:new, :create, :update, :destroy]
    resources :contact_sections, :only => [:new, :create, :update, :destroy]
    resources :download_sections, :only => [:new, :create, :update, :destroy]
    resources :downloads, :only => [:create]
    resources :embeds, :only => [:new, :create, :update, :destroy]
    resources :galleries, :only => [:new, :create, :update, :destroy]
    resources :gallery_images, :only => [:create]
    resources :hours, :only => [:new, :create, :update, :destroy]
    resources :newsletters, :only => [:new, :create, :update, :destroy]
    resources :services, :only => [:new, :create, :update, :destroy]
    resources :social_buttons, :only => [:new, :create, :update, :destroy]
    resources :social_feeds, :only => [:new, :create, :update, :destroy]
    resources :text_areas, :only => [:new, :create, :update, :destroy]
    resources :products, :only => [:new, :create, :update, :destroy]
    resources :iframes, :only => [:new, :create, :update, :destroy]
    resources :script_embeds, :only => [:new, :create, :update, :destroy]
    resources :paypal_buttons, :only => [:new, :create, :update, :destroy]
    resources :promotions, :only => [:new, :create, :update, :destroy]
  end
  
  match 'en/:pagename' => 'static#show'
  match 'en/:section/:pagename' => 'static#show'
  
  namespace :opgadmin do
    root :to => redirect("/opgadmin/users")
    resources :themes, :except => [:show] do
      put 'update_positions', :on => :collection
    end
    resources :users, :only => [:index, :show, :destroy, :edit, :update] do
      post 'cancel', :on => :member
      post 'activate', :on => :member
      post 'signin_as', :on => :member
    end
    resources :sites, :only => [:destroy] do
      post 'activate', :on => :member
      post 'clone', :on => :member
      post 'dont_renew_domain', :on => :member
    end
  end

  post '/api/users' => 'api#create_user'
  match 'api/paypal_callback' => 'api#paypal_callback'
  
  get '/sitemap' => 'static#sitemap'
  get '/sitemaps/:id' => 'static#sitemaps'
  get '/robots' => 'static#robots'
  get ':onepager_address' => 'pages#show'
  

end

app/controllers/account/whitelabels_controller.rb
class Account::WhitelabelsController < ApplicationController
  layout "account"
  ssl_required :edit, :update
  before_filter :require_user
  before_filter :load_site_and_page

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to edit_account_whitelabel_path, notice: 'Setting was successfully updated.' }
      else
        format.html { render "edit" }
      end
    end
  end
end

app/views/layouts/whitelabel/account.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= yield(:title) + ' | ' if content_for?(:title) %></title>
	<link rel="icon" type="image/png" href="/favicon.blue.ico" />
	<link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
	<!--[if lt IE 9]><script src="/javascripts/lib/shiv.modernizr.js" type="text/javascript"></script><![endif]-->
	
	<%= stylesheet_link_tag "whitelabel", :media => "all" %>
	<%= javascript_include_tag "dashboard" %>
	<%= yield :head_js %>
	
	<%= csrf_meta_tags %>
	
	<%= render :partial => "/shared/google_analytics" %>
</head>

<body<%= raw(' class="' + yield(:body_class) + '"' ) if content_for?(:body_class) %>>
	
	<section class="toolbar">
		<nav>
			<%= link_to current_user.white_label_title, account_sites_path, :class => 'logo' %>
			<div class="account_dropdown">
				<%= link_to 'Account', '/account/settings' %>
				<div class="dropdown">
					<%= link_to 'Profile', '/account/settings' if current_user.id != 8625 %>
					<%= link_to 'Sign Out', signin_path, :method => :delete %>
				</div>
			</div>
		</nav>
	</section>
	
	<section class="dashboard">
		<% if controller_name != 'sites' %>
			<nav>
				<%=raw dashboard_navigation(account_menu_items) %>
			</nav>
			<article>
				<%= yield %>
			</article>
		<% else %>
			<%= yield %>
		<% end %>
	</section>
		
	<%= yield :js_inject %>
</body>
</html>

app/views/layouts/whitelabel/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= yield(:title) + ' | ' if content_for?(:title) %></title>
	<link rel="icon" type="image/png" href="/favicon.blue.ico" />
	<link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
	<!--[if lt IE 9]><script src="/javascripts/lib/shiv.modernizr.js" type="text/javascript"></script><![endif]-->
	
	<%= stylesheet_link_tag "whitelabel", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= yield :head_js %>
	
	<%= csrf_meta_tags %>
	
	<%= render :partial => "/shared/google_analytics" %>
</head>
<body>
	<%= yield %>
	<%= yield :js_inject %>
</body>
</html>

app/views/layouts/whitelabel/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= yield(:title) + ' | ' if content_for?(:title) %></title>
	<link rel="icon" type="image/png" href="/favicon.blue.ico" />
	<link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
	<!--[if lt IE 9]><script src="/javascripts/lib/shiv.modernizr.js" type="text/javascript"></script><![endif]-->
	
	<%= stylesheet_link_tag "whitelabel", :media => "all" %>
	<%= javascript_include_tag "dashboard" %>
	<%= yield :head_js %>
	
	<%= csrf_meta_tags %>
	
	<%= render :partial => "/shared/google_analytics" %>
</head>

<body<%= raw(' class="' + yield(:body_class) + '"' ) if content_for?(:body_class) %>>
	
	<%= render 'shared/toolbar' if current_user %>
	
	<section class="dashboard_toolbar">
		<h1><%= @site.company_name %></h1>
		<nav>
			<a href="<%= edit_site_page_path(@site, @page) %>" class="edit_link">Edit Site</a>
			<a href="<%= @site.url_fullpath.gsub("onepagerapp.com", "easysiteadmin.com") %>" target="_blank" class="view_link">View Site</a>
		</nav>
	</section>
	
	<section class="dashboard">
		<nav>
			<%=raw dashboard_navigation(
				[
					{ :url => '/dashboard', :class => 'analytics_link', :name => 'Dashboard', :controller => 'analytics' },
					{ :url => '/dashboard/newsletter', :class => 'newsletter_link', :name => 'Newsletter', :controller => 'newsletters' },
					{ :url => '/dashboard/forms', :class => 'forms_link', :name => 'Form Submissions', :controller => 'forms' },
					{ :url => '/dashboard/setting', :class => 'settings_link', :name => 'Advanced', :controller => 'settings' }
				]
			) %>
		</nav>
		<article>
			<%= yield %>
		</article>
	</section>
	
	<%= yield :js_inject %>
</body>
</html>