config/routes.rb
Onepager::Application.routes.draw do
  root :to => 'static#index'
  
  resources :sites, :only => [:create, :show] do
    resources :pages, :only => [:show, :edit, :update] do
      member do
        put 'update_positions'
      end
    end
  end
  
  resource :signin, :controller => "user_sessions", :only => [:new, :create, :destroy], :path_names => { :new => "" }
  resource 'reset-password', :as => :reset_password, :controller => :reset_password, :only => [:new, :create, :edit, :update], :path_names => { :new => "" }
  resource :signup, :controller => "users", :only => [:new, :create], :path_names => { :new => "" } do
    collection do
      get 'get_city_state'
      get 'check_domain_availability'
      get 'validate_promo_code'
      get 'thankyou'
      post 'thankyou_survey'
    end
  end
  
  resources :themes, :only => [:show]
  
  resources :subscribers, :only => [:create] do
    member do
      get 'subscribe'
      get 'unsubscribe'
    end
  end
  post 'contact_form_responses' => 'contact_form_responses#create'
  post 'promotion_responses' => 'promotion_responses#create'
  
  get 'custom/:id.css' => 'pages#css'
  get 'custom/:id.ie.css' => 'pages#css_ie'
  
  namespace :dashboard do
    root :to => 'analytics#show'
    resource :newsletter, :only => [:new, :create], :path_names => { :new => "" } do
      collection do
        post 'confirm'
      end
    end
    get 'forms' => 'forms#index'
    get 'forms/:id' => 'forms#show'
    resources :subscribers, :only => [:index]
    resource :setting, :only => [:edit, :update, :destroy], :path_names => { :edit => "" }
    resource :domain, :controller => "sites", :only => [:edit, :update], :path_names => { :edit => "" } do
      put 'update_free_domain_user' => 'sites#update_free_domain_user'
    end
    get 'sites/:site_id/export' => 'sites#export'
  end
  
  namespace :account do
    resources :sites, :only => [:index, :create, :destroy]
    resource :affiliate, :only => [:show, :new, :create]
    
    get 'upgrade' => 'users#upgrade'
    put 'upgrade' => 'users#upgrade_update'
    post 'feedback' => 'users#feedback_send'
    
    resources :users, :except => [:show]
    resource :billing, :only => [:edit, :update]
    resources :billing, :controller => :billings, :only => [:index, :show]
    resource :settings, :only => [:edit, :update], :path_names => { :edit => "" }
    resource :whitelabel, :only => [:edit, :update], :path_names => { :edit => "" }
  end
  
  namespace :content_types do
    resources :buttons, :only => [:new, :create, :update, :destroy]
    resources :contact_form_fields, :only => [:new, :create, :update, :destroy]
    resources :contact_sections, :only => [:new, :create, :update, :destroy]
    resources :download_sections, :only => [:new, :create, :update, :destroy]
    resources :downloads, :only => [:create]
    resources :embeds, :only => [:new, :create, :update, :destroy]
    resources :galleries, :only => [:new, :create, :update, :destroy]
    resources :gallery_images, :only => [:create]
    resources :hours, :only => [:new, :create, :update, :destroy]
    resources :newsletters, :only => [:new, :create, :update, :destroy]
    resources :services, :only => [:new, :create, :update, :destroy]
    resources :social_buttons, :only => [:new, :create, :update, :destroy]
    resources :social_feeds, :only => [:new, :create, :update, :destroy]
    resources :text_areas, :only => [:new, :create, :update, :destroy]
    resources :products, :only => [:new, :create, :update, :destroy]
    resources :iframes, :only => [:new, :create, :update, :destroy]
    resources :script_embeds, :only => [:new, :create, :update, :destroy]
    resources :paypal_buttons, :only => [:new, :create, :update, :destroy]
    resources :promotions, :only => [:new, :create, :update, :destroy]
  end
  
  match 'en/:pagename' => 'static#show'
  match 'en/:section/:pagename' => 'static#show'
  
  namespace :opgadmin do
    root :to => redirect("/opgadmin/users")
    resources :themes, :except => [:show] do
      put 'update_positions', :on => :collection
    end
    resources :users, :only => [:index, :show, :destroy, :edit, :update] do
      post 'cancel', :on => :member
      post 'activate', :on => :member
      post 'signin_as', :on => :member
    end
    resources :sites, :only => [:destroy] do
      post 'activate', :on => :member
      post 'clone', :on => :member
      post 'dont_renew_domain', :on => :member
    end
  end

  post '/api/users' => 'api#create_user'
  match 'api/paypal_callback' => 'api#paypal_callback'
  
  get '/sitemap' => 'static#sitemap'
  get '/sitemaps/:id' => 'static#sitemaps'
  get '/robots' => 'static#robots'
  get ':onepager_address' => 'pages#show'
  

end

app/controllers/content_types/buttons_controller.rb
class ContentTypes::ButtonsController < ApplicationController
  layout false
  load_and_authorize_resource :except => :new
  
  def new
    @button = Button.new
    
    respond_to do |format|
      format.js
    end
  end
  
  def create
    @button = Button.new(params[:button])
    
    respond_to do |format|
      if @button.save
        format.js
      else
        format.js { render text: @button.errors.full_messages.join(", "), status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @button = Button.find(params[:id])
    
    respond_to do |format|
      if @button.update_attributes(params[:button])
        format.js
      else
        format.js { render text: @button.errors.full_messages.join(", "), status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @button = Button.find(params[:id])
    @button.destroy
    
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/content_types/contact_form_fields_controller.rb
class ContentTypes::ContactFormFieldsController < ApplicationController
  layout false
  load_and_authorize_resource :container, :parent => false, :except => :new
  
  def new
    @container = Container.new
    @container.default_contact_form_fields
    @container.title = "Contact Us"
    @container.format = current_user.email
    
    respond_to do |format|
      format.js
    end
  end
  
  def create
    merge_position_into_params!(params[:container][:contact_form_fields_attributes])
    @container = Container.new(params[:container])
    @container.child_object = "contact_form_fields"
    
    respond_to do |format|
      if @container.save
        @container.reload
        format.js
      else
        format.js { render text: @container.errors.full_messages.join(", "), status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @container = Container.find(params[:id])
    merge_position_into_params!(params[:container][:contact_form_fields_attributes])
    
    respond_to do |format|
      if @container.update_attributes(params[:container])
        @container.reload
        format.js
      else
        format.js { render text: @container.errors.full_messages.join(", "), status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @container = Container.find(params[:id])
    @container.destroy
    
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/content_types/contact_sections_controller.rb
class ContentTypes::ContactSectionsController < ApplicationController
  layout false
  load_and_authorize_resource :except => :new
  
  def new
    @contact_section = ContactSection.new
    @contact_section.title = "Contact Us"
    
    respond_to do |format|
      format.js
    end
  end
  
  def create
    @contact_section = ContactSection.new(params[:contact_section])
    @page = @contact_section.page
    
    respond_to do |format|
      if @contact_section.save
        format.js
      else
        format.js { render text: @contact_section.errors.full_messages.join(", "), status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @contact_section = ContactSection.find(params[:id])
    @page = @contact_section.page
    
    respond_to do |format|
      if @contact_section.update_attributes(params[:contact_section])
        format.js
      else
        format.js { render text: @contact_section.errors.full_messages.join(", "), status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @contact_section = ContactSection.find(params[:id])
    @contact_section.destroy
    
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/content_types/download_sections_controller.rb
class ContentTypes::DownloadSectionsController < ApplicationController
  layout false
  load_and_authorize_resource :container, :parent => false, :except => :new
  
  def new
    @container = Container.new
    @container.title = "Downloads"
    
    respond_to do |format|
      format.js
    end
  end
  
  def create
    merge_position_into_params!(params[:container][:downloads_attributes])
    @container = Container.new(params[:container])
    @container.child_object = "downloads"
    
    respond_to do |format|
      if @container.save
        @container.reload
        format.js
      else
        format.js { render text: @container.errors.full_messages.join(", "), status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @container = Container.find(params[:id])
    merge_position_into_params!(params[:container][:downloads_attributes])
    
    respond_to do |format|
      if @container.update_attributes(params[:container])
        @container.reload
        format.js
      else
        format.js { render text: @container.errors.full_messages.join(", "), status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @container = Container.find(params[:id])
    @container.destroy
    
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/content_types/downloads_controller.rb
class ContentTypes::DownloadsController < ApplicationController
  layout false
  
  def create
    @downloads = Array.new
    @errors = ""
    
    params[:download_files][0..30].each do |p|
      d = Download.new
      d.filename = p
      d.container_id = params[:container_id] if params[:container_id] != "new" # If container already exists, it gets passed in, otherwise its container-less and gets it container on container create
      d.save
      if d.valid?
        @downloads << d
      else
        @errors << d.errors.full_messages.join(", ")
      end
    end
    
    respond_to do |format|
      format.js { render }
    end
  end
end

app/controllers/content_types/embeds_controller.rb
class ContentTypes::EmbedsController < ApplicationController
  layout false
  load_and_authorize_resource :except => :new
  
  def new
    @embed = Embed.new
    
    respond_to do |format|
      format.js
    end
  end
  
  def create
    @embed = Embed.new(params[:embed])
    
    respond_to do |format|
      if @embed.save
        format.js
      else
        format.js { render text: @embed.errors.full_messages.join(", "), status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @embed = Embed.find(params[:id])
    
    respond_to do |format|
      if @embed.update_attributes(params[:embed])
        format.js
      else
        format.js { render text: @embed.errors.full_messages.join(", "), status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @embed = Embed.find(params[:id])
    @embed.destroy
    
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/content_types/galleries_controller.rb
class ContentTypes::GalleriesController < ApplicationController
  layout false
  load_and_authorize_resource :container, :parent => false, :except => :new
  
  def new
    @container = Container.new
    
    respond_to do |format|
      format.js
    end
  end
  
  def create
    merge_position_into_params!(params[:container][:gallery_images_attributes])
    @container = Container.new(params[:container])
    @container.child_object = "gallery_images"
    
    respond_to do |format|
      if @container.save
        @container.reload
        format.js
      else
        format.js { render text: @container.errors.full_messages.join(", "), status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @container = Container.find(params[:id])
    merge_position_into_params!(params[:container][:gallery_images_attributes])
    
    respond_to do |format|
      if @container.update_attributes(params[:container])
        @container.reload
        format.js
      else
        format.js { render text: @container.errors.full_messages.join(", "), status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @container = Container.find(params[:id])
    @container.destroy
    
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/content_types/gallery_images_controller.rb
class ContentTypes::GalleryImagesController < ApplicationController
  layout false
  
  def create
    @gallery_images = Array.new
    @errors = ""
    @format = params[:container][:format] if !params[:container][:format].blank?
    
    params[:gallery_image_files][0..30].each do |p|
      g = GalleryImage.new
      g.filename = p
      g.container_id = params[:container_id] if params[:container_id] != "new"
      g.save
      if g.valid?
        @gallery_images << g
      else
        @errors << g.errors.full_messages.join(", ")
      end
    end
    
    respond_to do |format|
      format.js { render }
    end
  end
end

app/controllers/content_types/hours_controller.rb
class ContentTypes::HoursController < ApplicationController
  layout false
  load_and_authorize_resource :container, :parent => false, :except => :new
  
  def new
    @container = Container.new
    @container.hours.build
    @container.title = "Hours"
    
    respond_to do |format|
      format.js
    end
  end
  
  def create
    @container = Container.new(params[:container])
    @container.child_object = "hours"
    
    respond_to do |format|
      if @container.save
        format.js
      else
        format.js { render text: @container.errors.full_messages.join(", "), status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @container = Container.find(params[:id])
    
    respond_to do |format|
      if @container.update_attributes(params[:container])
        format.js
      else
        format.js { render text: @container.errors.full_messages.join(", "), status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @container = Container.find(params[:id])
    @container.destroy
    
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/content_types/iframes_controller.rb
class ContentTypes::IframesController < ApplicationController
  layout false
  load_and_authorize_resource :except => :new
  
  def new
    @iframe = Iframe.new
    
    respond_to do |format|
      format.js
    end
  end
  
  def create
    @iframe = Iframe.new(params[:iframe])
    
    respond_to do |format|
      if @iframe.save
        format.js
      else
        format.js { render text: @iframe.errors.full_messages.join(", "), status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @iframe = Iframe.find(params[:id])
    
    respond_to do |format|
      if @iframe.update_attributes(params[:iframe])
        format.js
      else
        format.js { render text: @iframe.errors.full_messages.join(", "), status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @iframe = Iframe.find(params[:id])
    @iframe.destroy
    
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/content_types/newsletters_controller.rb
class ContentTypes::NewslettersController < ApplicationController
  layout false
  load_and_authorize_resource :container, :parent => false, :except => :new
  
  def new
    @container = Container.new
    @container.title = "Sign Up For Our Newsletter"
    
    respond_to do |format|
      format.js
    end
  end
  
  def create
    @container = Container.new(params[:container])
    @container.child_object = "newsletters"
    
    respond_to do |format|
      if @container.save
        format.js
      else
        format.js { render text: @container.errors.full_messages.join(", "), status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @container = Container.find(params[:id])
    
    respond_to do |format|
      if @container.update_attributes(params[:container])
        format.js
      else
        format.js { render text: @container.errors.full_messages.join(", "), status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @container = Container.find(params[:id])
    @container.destroy
    
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/content_types/paypal_buttons_controller.rb
class ContentTypes::PaypalButtonsController < ApplicationController
  layout false
  load_and_authorize_resource :except => :new
  
  def new
    @paypal_button = PaypalButton.new

    respond_to do |format|
      format.js
    end
  end
  
  def create
    @paypal_button = PaypalButton.new(params[:paypal_button])
        
    respond_to do |format|
      if @paypal_button.save
        format.js
      else
        format.js { render text: @paypal_button.errors.full_messages.join(", "), status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @paypal_button = PaypalButton.find(params[:id])
    
    respond_to do |format|
      if @paypal_button.update_attributes(params[:paypal_button])
        format.js
      else
        format.js { render text: @paypal_button.errors.full_messages.join(", "), status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @paypal_button = PaypalButton.find(params[:id])
    @paypal_button.destroy
    
    respond_to do |format|
      format.js
    end
  end
end

app/views/content_types/contact_form_fields/_content.html.erb
<%= content_tag(:h3, container.title) if !container.title.blank? %>
<%= content_tag(:p, container.description) if !container.description.blank? %>

<%= form_tag contact_form_responses_path, :remote => true, :id => 'new_contact_form_responses', :class => 'onepager_form new_contact_form_responses'  do %>
	<% container.contact_form_fields.each_with_index do |c, i| %>
		<fieldset>
			<%= label_tag "contact_form_responses[][value]", c.field_name %>
			<% if c.field_type == "text" %>
				<%= text_field_tag "contact_form_responses[][value]", '', :class => 'onepager_input' %>
			<% elsif c.field_type == "textarea" %>
				<%= text_area_tag "contact_form_responses[][value]", '', :class => 'onepager_input' %>
			<% end %>
			<%= hidden_field_tag "contact_form_responses[][contact_form_field_id]", c.id %>
		</fieldset>
	<% end %>
	<fieldset class="onepager_comments">
		<%= label_tag "comment", "Comment" %>
		<%= text_field_tag "comment" %>
	</fieldset>
	<div class="onepager_form_actions">
		<%= submit_tag I18n.t(:submit, :default => "Submit"), :class => 'onepager_submit' %>
	</div>
<% end %>

app/views/content_types/contact_form_fields/_form.html.erb
<section class="contact_form_fields" id="contact_form_fields_<%= container.id || 'new' %>" data-model-class="<%= container.class %>">
	<% if params[:action] != 'new' %>
		<div class="editable">
			<span class="form_edit">Click to Edit</span>
			<%= render "content_types/contact_form_fields/content", :container => container %>
		</div>
		<div class="addable">
			<a href="#" class="form_add">+ Add Content</a>
		</div>
	<% end %>
	
	<%= form_for [:content_types, container], :url => (container.new_record? ? content_types_contact_form_fields_path : content_types_contact_form_field_path(container)), :namespace => container.object_id, :remote => true do |f| %>
		<fieldset style="display: none;">
			<div class="form_header">
				<h6>Form</h6>
				<a href="#" class="form_info" data-content-type="contact_form_fields">Info</a>
			</div>
			<ul>
				<li>
					<%= f.label :title %>
					<%= f.text_field :title, :class => 'user_input', :size => '' %>
				</li>
				<li>
					<%= f.label :description %>
					<%= f.text_area :description, :class => 'user_input', :size => '' %>
				</li>
			</ul>
			<div class="content_list">
				<h6>Form Fields</h6>
				<ul>
					<%= f.fields_for :contact_form_fields do |c| %>
						<li>
							<%= c.label :field_name %>
							<%= c.text_field :field_name, :size => '' %>
							<%= c.label :field_type %>
							<%= c.select :field_type, ContactFormField::FIELD_TYPES %>
							<div class="checkbox">
								<%= c.check_box :required %><%= c.label :required %>
							</div>
							<%= c.hidden_field :_destroy %>
							<%= c.hidden_field :id %>
							<a href="#" class="remove_item">Delete</a> <%# show this delete button only if there is more than 1 %>
						</li>
					<% end %>
				</ul>
				<a href="#" class="add_item">Add Field</a>
			</div>
			<ul>
				<li>
					<%# Email for contact form is stored in container.format %>
					<%= f.label :format, "Email Form Submissions To" %>
					<%= f.text_field :format, :class => 'user_input', :size => '', :placeholder => 'e.g. hi@onepagerapp.com' %>
				</li>
			</ul>
			<div class="form_actions">
				<%= link_to "Delete?", content_types_contact_form_field_path(container), :class => 'form_remove', :method => :delete, :remote => true, :data => { :confirm => 'Delete?' } if params[:action] != 'new' %>
				<a href="#" class="form_close">Cancel</a>
				<%= f.hidden_field :page_id, :value => page_id %>
				<%= f.hidden_field :position, :value => position if defined? position %>
				<%= f.submit "Done", :class => 'user_submit' %>
			</div>
		</fieldset>
	<% end %>
</section>

app/views/content_types/contact_form_fields/create.js.erb
Onepager.ContactFormFields.create( {
	content: '<%= escape_javascript(render 'form', :container => @container, :page_id => @container.page_id) %>',
	id: <%= @container.id %>
} );

app/views/content_types/contact_form_fields/destroy.js.erb
Onepager.ContactFormFields.destroy( <%= @container.id %> );

app/views/content_types/contact_form_fields/new.js.erb
Onepager.ContactFormFields.add('<%= escape_javascript(render 'form', :container => @container, :page_id => params[:page_id], :position => params[:position]) %>');

app/views/content_types/contact_form_fields/update.js.erb
Onepager.ContactFormFields.update( {
	content: '<%= escape_javascript(render 'form', :container => @container, :page_id => @container.page_id) %>',
	id: <%= @container.id %>
} );