config/routes.rb
Onepager::Application.routes.draw do
  root :to => 'static#index'
  
  resources :sites, :only => [:create, :show] do
    resources :pages, :only => [:show, :edit, :update] do
      member do
        put 'update_positions'
      end
    end
  end
  
  resource :signin, :controller => "user_sessions", :only => [:new, :create, :destroy], :path_names => { :new => "" }
  resource 'reset-password', :as => :reset_password, :controller => :reset_password, :only => [:new, :create, :edit, :update], :path_names => { :new => "" }
  resource :signup, :controller => "users", :only => [:new, :create], :path_names => { :new => "" } do
    collection do
      get 'get_city_state'
      get 'check_domain_availability'
      get 'validate_promo_code'
      get 'thankyou'
      post 'thankyou_survey'
    end
  end
  
  resources :themes, :only => [:show]
  
  resources :subscribers, :only => [:create] do
    member do
      get 'subscribe'
      get 'unsubscribe'
    end
  end
  post 'contact_form_responses' => 'contact_form_responses#create'
  post 'promotion_responses' => 'promotion_responses#create'
  
  get 'custom/:id.css' => 'pages#css'
  get 'custom/:id.ie.css' => 'pages#css_ie'
  
  namespace :dashboard do
    root :to => 'analytics#show'
    resource :newsletter, :only => [:new, :create], :path_names => { :new => "" } do
      collection do
        post 'confirm'
      end
    end
    get 'forms' => 'forms#index'
    get 'forms/:id' => 'forms#show'
    resources :subscribers, :only => [:index]
    resource :setting, :only => [:edit, :update, :destroy], :path_names => { :edit => "" }
    resource :domain, :controller => "sites", :only => [:edit, :update], :path_names => { :edit => "" } do
      put 'update_free_domain_user' => 'sites#update_free_domain_user'
    end
    get 'sites/:site_id/export' => 'sites#export'
  end
  
  namespace :account do
    resources :sites, :only => [:index, :create, :destroy]
    resource :affiliate, :only => [:show, :new, :create]
    
    get 'upgrade' => 'users#upgrade'
    put 'upgrade' => 'users#upgrade_update'
    post 'feedback' => 'users#feedback_send'
    
    resources :users, :except => [:show]
    resource :billing, :only => [:edit, :update]
    resources :billing, :controller => :billings, :only => [:index, :show]
    resource :settings, :only => [:edit, :update], :path_names => { :edit => "" }
    resource :whitelabel, :only => [:edit, :update], :path_names => { :edit => "" }
  end
  
  namespace :content_types do
    resources :buttons, :only => [:new, :create, :update, :destroy]
    resources :contact_form_fields, :only => [:new, :create, :update, :destroy]
    resources :contact_sections, :only => [:new, :create, :update, :destroy]
    resources :download_sections, :only => [:new, :create, :update, :destroy]
    resources :downloads, :only => [:create]
    resources :embeds, :only => [:new, :create, :update, :destroy]
    resources :galleries, :only => [:new, :create, :update, :destroy]
    resources :gallery_images, :only => [:create]
    resources :hours, :only => [:new, :create, :update, :destroy]
    resources :newsletters, :only => [:new, :create, :update, :destroy]
    resources :services, :only => [:new, :create, :update, :destroy]
    resources :social_buttons, :only => [:new, :create, :update, :destroy]
    resources :social_feeds, :only => [:new, :create, :update, :destroy]
    resources :text_areas, :only => [:new, :create, :update, :destroy]
    resources :products, :only => [:new, :create, :update, :destroy]
    resources :iframes, :only => [:new, :create, :update, :destroy]
    resources :script_embeds, :only => [:new, :create, :update, :destroy]
    resources :paypal_buttons, :only => [:new, :create, :update, :destroy]
    resources :promotions, :only => [:new, :create, :update, :destroy]
  end
  
  match 'en/:pagename' => 'static#show'
  match 'en/:section/:pagename' => 'static#show'
  
  namespace :opgadmin do
    root :to => redirect("/opgadmin/users")
    resources :themes, :except => [:show] do
      put 'update_positions', :on => :collection
    end
    resources :users, :only => [:index, :show, :destroy, :edit, :update] do
      post 'cancel', :on => :member
      post 'activate', :on => :member
      post 'signin_as', :on => :member
    end
    resources :sites, :only => [:destroy] do
      post 'activate', :on => :member
      post 'clone', :on => :member
      post 'dont_renew_domain', :on => :member
    end
  end

  post '/api/users' => 'api#create_user'
  match 'api/paypal_callback' => 'api#paypal_callback'
  
  get '/sitemap' => 'static#sitemap'
  get '/sitemaps/:id' => 'static#sitemaps'
  get '/robots' => 'static#robots'
  get ':onepager_address' => 'pages#show'
  

end

app/models/theme.rb
class Theme < ActiveRecord::Base
  # attr_accessible :title, :body
  
  has_many :sites
  
  validates :theme_name, :presence => true
  validates :screenshot_image, :presence => true
  
  hex_format = /^[0-9A-F]+$/i
  validates :header_colour, :presence => true, :format => hex_format
  validates :subheader_colour, :presence => true, :format => hex_format
  validates :body_colour, :presence => true, :format => hex_format
  validates :background_colour, :presence => true, :format => hex_format
  validates :content_background_colour, :presence => true, :format => hex_format
  
  validates :content_background_opacity, :presence => true, :numericality => true
  
  validates :header_type, :presence => true
  validates :subheader_type, :presence => true
  validates :body_type, :presence => true
  
  validates :header_size, :presence => true, :numericality => true
  validates :subheader_size, :presence => true, :numericality => true
  validates :body_size, :presence => true, :numericality => true
  
  mount_uploader :background_image, BackgroundImageUploader
  mount_uploader :screenshot_image, BackgroundImageUploader
end

app/controllers/opgadmin/sites_controller.rb
class Opgadmin::SitesController < ApplicationController
  before_filter :admin_authenticate
  ssl_required :destroy, :activate, :clone, :dont_renew_domain

  def destroy
  	s = Site.find(params[:id])
  	s.active = false
  	s.save

  	redirect_to opgadmin_user_url(s.user), notice: "#{s.company_name} site was successfully deactivated."
  end

  def activate
  	s = Site.unscoped.find(params[:id])
  	s.active = true
  	s.save

  	redirect_to opgadmin_user_url(s.user), notice: "#{s.company_name} site was successfully activated."
  end

  def clone
    ActiveRecord::Base.observers.disable :all
    original_site = Site.find(params[:id])
    new_site = original_site.dup
    new_site.domain_type = "no_custom_domain"
    new_site.onepager_address = new_site.trial_address
    new_site.logo_image = File.open(original_site.logo_image.current_path)
    new_site.save

    original_site.pages.each do |p|
      new_page = p.dup
      new_page.site_id = new_site.id
      new_page.save
      p.buttons.each do |b|
        new_button = b.dup
        new_button.page_id = new_page.id
        new_button.save
      end
      p.contact_sections.each do |cs|
        new_cs = cs.dup
        new_cs.page_id = new_page.id
        new_cs.save
      end
      p.containers.each do |c|
        new_container = c.dup
        new_container.page_id = new_page.id

        c.contact_form_fields.each do |cff|
          new_cff = cff.dup
          new_cff.save
          new_container.contact_form_fields << new_cff
        end
        c.downloads.each do |d|
          new_download = d.dup
          new_download.filename = d.filename
          new_download.save
          new_container.downloads << new_download
        end
        c.gallery_images.each do |gi|
          new_gi = gi.dup
          new_gi.filename = File.open(gi.filename.current_path)
          new_gi.save
          new_container.gallery_images << new_gi
        end
        c.hours.each do |h|
          new_hour = h.dup
          new_hour.save
          new_container.hours << new_hour
        end
        c.services.each do |s|
          new_service = s.dup
          new_service.save
          new_container.services << new_service
        end
        if c.social_button
          new_social_button = c.social_button.dup
          new_social_button.container_id = new_container.id
          new_social_button.save
          c.social_button.social_links.each do |sl|
            new_social_link = sl.dup
            new_social_link.social_button_id = new_social_button.id
            new_social_link.save
          end
          new_container.social_button = new_social_button
        end

        new_container.save
      end
      p.embeds.each do |e|
        new_embed = e.dup
        new_embed.page_id = new_page.id
        new_embed.save
      end
      p.iframes.each do |i|
        new_iframe = i.dup
        new_iframe.page_id = new_page.id
        new_iframe.save
      end
      p.social_feeds.each do |sf|
        new_sf = sf.dup
        new_sf.page_id = new_page.id
        new_sf.save
      end
      p.text_areas.each do |t|
        new_text_area = t.dup
        new_text_area.page_id = new_page.id
        new_text_area.save
      end
    end
    ActiveRecord::Base.observers.enable :all

    redirect_to opgadmin_user_url(original_site.user), notice: "#{original_site.company_name} site was successfully cloned."
  end

  def dont_renew_domain
    require 'opensrs'

    server = Site.opensrs_server

    site = Site.find(params[:id])

    response = server.call(
      :action => "modify",
      :object => "domain",
      :domain => site.purchased_domain,
      :attributes => {
        :data => "expire_action",
        :affect_domains => 0,
        :auto_renew => 0,
        :let_expire => 0,
        :domain => site.purchased_domain
      }
    )
    if response.success?
      redirect_to opgadmin_user_url(site.user), notice: "#{site.purchased_domain}'s account was successfully dont renew domain'd."
    else
      redirect_to opgadmin_user_url(site.user), notice: "An error occurred while dont renew domain #{site.purchased_domain}. #{response.response}"
    end
  end
end

app/controllers/opgadmin/themes_controller.rb
class Opgadmin::ThemesController < ApplicationController
  layout 'admin'
  before_filter :admin_authenticate
  ssl_required :index, :new, :create, :edit, :update, :destroy, :update_positions
  
  def index
    @themes = Theme.order(:position)
  end
  
  def new
    @theme = Theme.new
  end
  
  def create
    @theme = Theme.new(params[:theme])
    
    if @theme.save
      redirect_to opgadmin_themes_path
    else
      render "new"
    end
  end
  
  def edit
    @theme = Theme.find(params[:id])
  end
  
  def update
    @theme = Theme.find(params[:id])
    
    respond_to do |format|
      if @theme.update_attributes(params[:theme])
        format.html { redirect_to [:edit, :opgadmin, @theme], notice: 'Theme was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end
  
  def destroy
    @theme = Theme.find(params[:id])
    @theme.destroy
    
    redirect_to opgadmin_themes_path
  end
  
  
  def update_positions
    theme_ids = params[:theme]
    Theme.transaction do
      theme_ids.each_with_index do |s, i|
        Theme.update_all ["position = ?", i], ["id = ?", s]
      end
    end
    head :ok
  end
end

app/controllers/opgadmin/users_controller.rb
class Opgadmin::UsersController < ApplicationController
  layout 'admin'
  before_filter :admin_authenticate
  ssl_required :index, :show, :update, :cancel, :activate, :destroy, :signin_as
  
  def index
    @users = User.where("users.id IS NOT NULL").paginate(:page => params[:page])
    @users = @users.where("payment_plan = :plan", :plan => "#{params[:plan]}") if !params[:plan].blank?
    @users = @users.where("active = :bool", :bool => params[:active]) if !params[:active].blank?
    @users = @users.joins(:sites).where("users.email LIKE :query OR concat(users.first_name, ' ', users.last_name) LIKE :query OR sites.company_name LIKE :query OR sites.onepager_address LIKE :query OR sites.domain_name LIKE :query", :query => "%#{params[:search]}%") if !params[:search].blank?
  end
  
  def show
    @user = User.find(params[:id])
    @sites = @user.sites.unscoped.where("user_id = #{@user.id}")
    @affiliate = Affiliate.find_by_user_id(@user.id) if @user.is_affiliate?
  end
  
  def update
    u = User.find(params[:id])
    u.update_column(:allow_script_embeds, !u.allow_script_embeds)
    redirect_to request.referrer, notice: "#{u.email} was successfully updated."
  end
  
  def cancel
    u = User.find(params[:id])
    u.cancellation_date = params[:cancellation_date]
    u.payment_frequency = "Trial"
    u.payment_plan = "Trial"
    u.sites.each do |s|
      s.domain_type = "no_custom_domain"
      s.onepager_address = s.trial_address
      s.save
    end
    if u.save!
      begin
        p = u.payments.last
        gateway.cancel_recurring(p.subscriber_id_monthly) if !p.subscriber_id_monthly.blank?
        gateway.cancel_recurring(p.subscriber_id_annual) if !p.subscriber_id_annual.blank?
        Recurly::Subscription.find(u.recurly_subscription_uuid).cancel if !u.recurly_subscription_uuid.blank? 
      rescue
        PostOffice.send_simple_message("#{u.email}'s account cancelled with errors", "#{u.email} did not have payments entries in the database but their account was cancelled.  Look into it. #{opgadmin_user_path(u)}")
      end
      redirect_to opgadmin_user_path(u), notice: "#{u.email}'s account was successfully cancelled."
    else
      redirect_to opgadmin_user_path(u), notice: "An error occurred while cancelling #{u.email}'s account."
    end

  end

  def activate
    u = User.find(params[:id])
    u.update_column(:active, true)
    Site.unscoped.where(:user_id => u.id).each do |s|
      s.active = true
      s.save
    end
    redirect_to request.referrer, notice: "#{u.email} was successfully reactivated."
  end

  def destroy
    u = User.find(params[:id])
    u.update_column(:active, false)
    u.sites.each do |s|
      s.update_column(:active, false)
    end

    # u = User.find(params[:id])
    # u.sites.each do |s|
    #   s.pages.each do |p|
    #     p.content.each do |c|
    #       c.destroy
    #     end
    #     p.destroy
    #   end
    #   s.analytics.each do |a|
    #     a.destroy
    #   end
    #   Newsletter.where(:site_id => s.id).each do |n|
    #     n.destroy
    #   end
    #   s.destroy
    # end
    # u.payments.each do |p|
    #   p.destroy
    # end
    # u.destroy
    
    redirect_to request.referrer, notice: "#{u.email} was successfully deactivated."
  end

  def signin_as
    @user = User.find(params[:id])
    UserSession.create(@user)
    redirect_to "/account/sites"
  end

  def gateway
    ActiveMerchant::Billing::Base.gateway('authorize_net').new(:login => APP_CONFIG['authorize_login'], :password => APP_CONFIG['authorize_password'], :test => APP_CONFIG['authorize_test'])
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  def show
    @theme = Theme.find(params[:id])
    
    respond_to do |format|
      format.json
    end
  end
end

app/views/opgadmin/themes/_form.html.erb
<% if action_name != 'new' %>
	<% content_for :head_css do %>

		<style type="text/css" media="screen">
			h1 {
				font-family: <%=raw get_font_stack(@theme.header_type) %>; font-weight: <%=raw get_font_weight(@theme.header_type) %>; color: #<%= @theme.header_colour %>; font-size: <%= @theme.header_size %>px;
			}
				h1 img {
					max-width: 100%;
				}
			h2, h3 {
				font-family: <%=raw get_font_stack(@theme.subheader_type) %>; font-weight: <%=raw get_font_weight(@theme.subheader_type) %>; color: #<%= @theme.subheader_colour %>;
			}
			h2 {
				font-size: <%= @theme.subheader_size %>px;
			}
			h3 {
				font-size: <%= @theme.subheader_size * 0.65 %>px;
			}
			body {
				color: #<%= @theme.body_colour %>; font-family: <%=raw get_font_stack(@theme.body_type) %>; font-weight: <%=raw get_font_weight(@theme.body_type) %>; font-size: <%= @theme.body_size %>px;
				background-color: #<%= @theme.background_colour %>; background-image: url('<%= @theme.background_image_enabled ? @theme.background_image : '' %>');
				background-repeat: <%= @theme.background_image_alignment == 'center' ? 'no-repeat' : 'repeat'; %>; background-attachment: <%= @theme.background_image_fixed ? 'fixed' : 'scroll' %>;
				background-size: <%= @theme.background_image_alignment %>; -moz-background-size: <%= @theme.background_image_alignment %>; -webkit-background-size: <%= @theme.background_image_alignment %>;
			}
				article {
					background-color: rgba(<%= hex_to_rgb(@theme.content_background_colour) %>, <%= @theme.content_background_opacity.to_f / 100 %>);
					width: 450px; padding: 25px 30px;
				}
		</style>

	<% end %>
<% end %>

<article class="theme_editor">
	<header>
		<h1><%= @theme.theme_name || 'My Company Name' %></h1>
		<h2>Bacon ipsum dolor sit amet spare ribs pork belly.</h2>
	</header>
	
	<section class="text_areas">
		<h3>Header Lorem Ipsum</h3>
		<p>Lorem Ipsum Dolorean Consequitor asasdf asdfdf asdf</p>
	</section>
	<section class="buttons">
		<a href="http://google.com" class="call_to_action_button">adf asdf</a>
	</section>
	<section class="services">
		<h3>Our Services</h3>
		<p>asdf asdf asdf asdf</p>
		<ul>
			<li>adf asdf asdf asdf </li>
			<li>adsf asdf asdf asdf asdf </li>
		</ul>
	</section>
	<section class="contact_form_fields">
		<h3>Contact Us</h3>
		<p>adf asdf asdf asdf adsf</p>

		<form class="onepager_form">
			<fieldset>
				<label for="contact_form_responses__value">Name</label>
				<input class="onepager_input" type="text" value="" />
			</fieldset>
			<fieldset>
				<label for="contact_form_responses__value">Email</label>
				<input class="onepager_input" type="text" value="" />
			</fieldset>
			<fieldset>
				<label for="contact_form_responses__value">Message</label>
				<textarea class="onepager_input"></textarea>
			</fieldset>
			<div class="onepager_form_actions">
				<input class="onepager_submit" name="commit" type="submit" value="Submit" />
			</div>
		</form>
	</section>
	<section class="embeds">
		<h3>asdfasdfasdf</h3>
		<p>asdfasdfasdf</p>
		<iframe width="430" height="242" src="https://www.youtube.com/embed/YLO7tCdBVrA?fs=1&feature=oembed" frameborder="0" allowfullscreen></iframe>
	</section>
	<section class="contact_sections">
		<h3>Contact Us</h3>
		<p>adsf asdf adsf</p>
		<ul>
			<li itemprop="telephone">555-555-5555</li>
			<li itemprop="faxNumber">555-555-5556 (Fax)</li>
			<li itemprop="email"><a href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;%65%6d%61%69%6c@%67%6d%61%69%6c.%63%6f%6d">email@gmail.com</a></li>
			<li itemprop="address" itemscope itemtype="http://schema.org/PostalAddress"><span itemprop="streetAddress">123 Main St</span><br />Suite 5<br /><span itemprop="addressLocality">New York</span>, <span itemprop="addressRegion">NY</span>  <span itemprop="postalCode">10022</span></li>
		</ul>
		<a href="http://maps.google.com/maps?q=123+Main+St+Suite+5+New+York%2C+NY+10022" target="_blank" itemprop="maps" class="map">
			<img src="https://maps.google.com/maps/api/staticmap?center=123+Main+St+Suite+5+New+York%2C+NY+10022&zoom=15&size=450x300&maptype=roadmap&markers=color:red%7Ccolor:red%7C123+Main+St+Suite+5+New+York%2C+NY+10022&sensor=false&key=AIzaSyCJeGbqsAE52iUiWBc__AnQ-5YBjskkuo0" width="100%" />
		</a>
	</section>
	<section class="hours">
		<h3>Hours</h3>
		<p>adsf asdf asdf asdf asdf asdf asdf asdf </p>
		<ul>
			<li><strong>Mon - Wed, Fri</strong> <span>9:00 AM - 5:00 PM</span></li>
			<li><strong>Thu</strong> <span>9:00 AM - 7:00 PM</span></li>
			<li><strong>Sat - Sun</strong> <span>11:00 AM - 5:00 PM</span></li>
		</ul>
	</section>
	<section class="social_buttons">
		<h3>Social</h3>
		<p>adf adf asdf asdf asdf asdf asdf </p>
		<a href="http://facebook.com/onepagerapp"><img src="/assets/pages/social-buttons/facebook.png" target="_blank" alt="Facebook" /></a>
		<a href="http://twitter.com/onepagerapp"><img src="/assets/pages/social-buttons/twitter.png" target="_blank" alt="Twitter" /></a>
		<a href="http://linkedin.com/company/onepagerapp"><img src="/assets/pages/social-buttons/linkedin.png" target="_blank" alt="LinkedIn" /></a>
		<a href="http://onepagerapp.tumblr.com"><img src="/assets/pages/social-buttons/blog.png" target="_blank" alt="Blog" /></a>
		<a href="http://onepagerapp.tumblr.com"><img src="/assets/pages/social-buttons/tumblr.png" target="_blank" alt="tumblr" /></a>
		<a href="http://youtube.com/onepagerapp"><img src="/assets/pages/social-buttons/youtube.png" target="_blank" alt="YouTube" /></a>
		<a href="http://vimeo.com/onepagerapp"><img src="/assets/pages/social-buttons/vimeo.png" target="_blank" alt="Vimeo" /></a>

		<div class="like_buttons">
			<a href="https://twitter.com/share" class="twitter-share-button" data-count="none" data-lang="en">Tweet</a>
			<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

			<!-- Place this tag where you want the +1 button to render. -->
			<div class="g-plusone" data-size="medium" data-annotation="none"></div>

			<!-- Place this tag after the last +1 button tag. -->
			<script type="text/javascript">
			(function() {
				var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
				po.src = 'https://apis.google.com/js/plusone.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
			})();
			</script>

			<script>(function(d, s, id) {
				var js, fjs = d.getElementsByTagName(s)[0];
				if (d.getElementById(id)) return;
				js = d.createElement(s); js.id = id;
				js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
				fjs.parentNode.insertBefore(js, fjs);
				}(document, 'script', 'facebook-jssdk'));</script>
				<div class="fb-like" data-href="http%3A%2F%2Flocalhost%3A3000%2Fsites%2F1%2Fpages%2F1" data-send="false" data-layout="button_count" data-width="90" data-show-faces="false"></div>
				<div id="fb-root"></div>
			</div>
	</section>
	<section class="newsletters">
		<h3>Sign Up For Our Newsletter</h3>
		<p>adsf adsf asdf asdf adsf </p>
		<form class="new_subscriber">
			<fieldset>
				<input class="onepager_input" placeholder="Enter your email address" size="30" type="text" />
				<input class="onepager_submit" name="commit" type="submit" value="Subscribe" />
			</fieldset>
		</form>
	</section>
	<section class="galleries">
		<h3>Images</h3>
		<img alt="" src="/uploads/gallery_image/444/thumbnail_907-original.jpg" />
		<img alt="" src="/uploads/gallery_image/445/thumbnail_908-original.jpg" />
		<img alt="" src="/uploads/gallery_image/446/thumbnail_909-original.jpg" />
	</section>
	<footer>
		&copy; 2016 <span>My Company Name</span>
	</footer>
</article>

<section class="theme_selector">
	
	<% if @theme.errors.any? %>
		<div class="errors">
			<%= flash[:notice] %>
			<%= @theme.errors.full_messages.join(", ") if !@theme.errors.blank? %>
		</div>
	<% end %>
	<% if !flash[:notice].blank? %>
		<div class="notice">
			<%= flash[:notice] %>
		</div>
	<% end %>
	
	<%= form_for [:opgadmin, @theme], :html => { :enctype => "multipart/form-data" } do |f| %>
	
		<fieldset>
			<ul>
				<li>
					<%= f.label :theme_name %>
					<%= f.text_field :theme_name, :class => 'user_input', :size => '' %>
				</li>
				<li>
					<%= f.label :screenshot_image %>
					<%= f.file_field :screenshot_image %>
					<%= image_tag @theme.screenshot_image, :alt => '' if !@theme.screenshot_image.blank? %>
				</li>
			</ul>
		</fieldset>
	
		<fieldset>
			<ul>
				<li class="colorpicker">
					<%= f.label :background_colour, 'Page Background Color' %>
					<%= f.text_field :background_colour, :class => 'user_input short_input', :size => '', :placeholder => 'Color', :maxlength => 6 %>
				</li>
				<li>
					<%= f.label :background_image, 'Page Background Image' %>
					<%= f.file_field :background_image %>
					<%= f.select :background_image_alignment, Site::ALIGNMENTS %>
					<div class="checkbox">
						<%= f.check_box :background_image_fixed %>
						<%= f.label :background_image_fixed, 'Fixed in place' %>
					</div>
					<%= image_tag @theme.background_image, :alt => '' if !@theme.background_image.blank? %>
					<div class="checkbox">
						<%= f.check_box :background_image_enabled %>
						<%= f.label :background_image_enabled, 'Display background image' %>
					</div>
				</li>
			</ul>
		</fieldset>
		<fieldset>
			<ul>
				<li class="colorpicker">
					<%= f.label :content_background_colour, 'Content Background' %>
					<%= f.text_field :content_background_colour, :class => 'user_input short_input', :size => '', :placeholder => 'Color', :maxlength => 6 %>
					<%= f.text_field :content_background_opacity, :class => 'user_input short_input', :size => '', :placeholder => 'Opacity', :maxlength => 3 %>
				</li>
			</ul>
		</fieldset>
		<fieldset>
			<ul>
				<li>
					<%= f.label :header_type, 'Company Font' %>
					<%= f.select :header_type, font_select() %>
				</li>
				<li>
					<%= f.label :subheader_type, 'Header Font' %>
					<%= f.select :subheader_type, font_select() %>
				</li>
				<li>
					<%= f.label :body_type, 'Body Font' %>
					<%= f.select :body_type, font_select( Site::FONTS['safe'] + Site::FONTS['basic'] ) %>
				</li>
				<li class="colorpicker">
					<%= f.label :header_colour, 'Header Styles' %>
					<%= f.text_field :header_colour, :class => 'user_input short_input', :size => '', :placeholder => 'Color', :maxlength => 6 %>
					<%= f.text_field :header_size, :class => 'user_input short_input', :size => '', :placeholder => 'Size' %>
				</li>
				<li class="colorpicker">
					<%= f.label :subheader_colour, 'Subheader Styles' %>
					<%= f.text_field :subheader_colour, :class => 'user_input short_input', :size => '', :placeholder => 'Color', :maxlength => 6 %>
					<%= f.text_field :subheader_size, :class => 'user_input short_input', :size => '', :placeholder => 'Size' %>
				</li>
				<li class="colorpicker">
					<%= f.label :body_colour, 'Body Font Styles' %>
					<%= f.text_field :body_colour, :class => 'user_input short_input', :size => '', :placeholder => 'Color', :maxlength => 6 %>
					<%= f.text_field :body_size, :class => 'user_input short_input', :size => '', :placeholder => 'Size' %>
				</li>
			</ul>
		</fieldset>
		<div class="form_actions">
			<%= f.submit 'Apply Theme', :class => 'user_submit' %>
			<%= link_to 'Cancel', opgadmin_themes_path %>
		</div>
	
	<% end %>
</section>

<% content_for :js_inject do %>
	<script type="text/javascript">
		OnepagerAdmin.Theme.edit(<%= @theme.id || "'new'" %>);
	</script>
<% end %>

app/views/opgadmin/themes/edit.html.erb
<%= render 'form' %>

app/views/opgadmin/themes/index.html.erb
<% content_for :header do %>
	<%= link_to '+ New Theme', new_opgadmin_theme_path, :class => 'general_button' %>
<% end %>

<article class="theme_list">
	<ol data-url="/admin/themes/update_positions">
		<% @themes.each do |t| %>
			<li id="theme_<%= t.id %>">
				<h2><%= link_to t.theme_name, edit_opgadmin_theme_path(t) %></h2>
				<%= image_tag t.screenshot_image, :alt => '' %>
				<div class="theme_actions">
					<%= link_to 'Edit', edit_opgadmin_theme_path(t) %>
					<%= link_to 'Delete', opgadmin_theme_path(t), :method => :delete, :confirm => 'Are you sure you want to delete this theme?' %>
				</div>
			</li>
		<% end %>
	</ol>
</article>

<% content_for :js_inject do %>
	<script type="text/javascript">
		OnepagerAdmin.Theme.load();
	</script>
<% end %>

app/views/opgadmin/themes/new.html.erb
<%= render 'form' %>